name: dnd_vault
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.006

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  http: ^1.4.0
  js: ^0.7.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: dndFont
      fonts:
        - asset: assets/fonts/DragonHunter.otf
  assets:
    - assets/images/

